"""Update book model

Revision ID: 40e9d9ca6892
Revises: d71ed5ebfb62
Create Date: 2025-03-25 00:04:12.488452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e9d9ca6892'
down_revision: Union[str, None] = 'd71ed5ebfb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('books_authors_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    op.drop_column('books', 'authors_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('authors_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_authors_id_fkey', 'books', 'authors', ['authors_id'], ['id'])
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
